version: '3'

services:
  
  api:
    container_name: api
    restart: 'always'
    build:
      context: './'
      dockerfile: 'production.Dockerfile'
    expose:
      - "${PORT}"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.priority=100"
      - "traefik.http.routers.api.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    env_file:
      - .env
  
networks:
  web:
    external:
      name: ${TRAEFIK_NETWORK}
